#!/usr/bin/env sh

FILES=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g')

if [ "${FILES}" != "" ]; then
    PHP_FILES=$(echo "${FILES}" | grep '\.php' | xargs)

    if [ "${PHP_FILES}" != "" ]; then
        FILES=$(echo "${PHP_FILES}" | grep -vw vendor | xargs) npm exec just format php
    fi

    FILES=$(echo "${FILES}" | xargs) npm exec just format all

    git update-index --again

    npm exec just setup commit

    exit 0
else
    echo "No files committed!"

    exit 255
fi
